"""Master monster table for the MH Rise Archipelago world.

Single source of truth for which monsters are randomizable, what their
in-game EmType ID is, and which DLC bucket they belong to. The Python
apworld imports MONSTERS to build item/location tables; the in-game Lua
client receives the same data over slot_data so the two sides cannot drift.

Generated by hand-curating mhrise_em_types.json (produced by the
client/HelloWorld.lua dump tool). Source data: 117 EmTypes enum entries.

Each entry is a dict with keys:
- name: display name (AP item/location names derive from this)
- em_type: in-game enum value (snow.enemy.EnemyDef.EmTypes)
- enum_name: original enum field name; kept for debugging
- dlc: "rise" or "sunbreak"
- tags: list of strings used for additive categorisation. Consumers should
  match by `"foo" in m["tags"]`, never by equality. Current tags in use:
    - "elder-dragon": for HuntAThon goal selection.
    - "risen": Risen variant; gated by the IncludeRisen option.
    - "non-randomizable": engine-special monsters with bespoke arena
      setup (Ibushi, Narwa, Gaismagorm, Narwa the Allmother). Excluded
      from BOTH swap-source and swap-target pools in QuestRando mode
      because they crash on spawn in non-bespoke quest contexts.

Curation decisions for v1:
- Placeholder enum slots (display_name = "未指定") dropped.
- Apex variants (_07 suffix) kept in APEX_MONSTERS but excluded from
  MONSTERS: they appear only in rampage quests and don't fit a license
  model. A future option can enable them.
- Small monsters kept in SMALL_MONSTERS but excluded from MONSTERS: not
  huntable in the AP sense for v1. A future option can enable them.
"""

from __future__ import annotations
from typing import Any


# Large monsters available in the base game (Rise).
RISE_MONSTERS: tuple[dict[str, Any], ...] = (
    {"name": "Rathian",                "em_type":   1, "enum_name": "EmType001_00", "dlc": "rise", "tags": []},
    {"name": "Rathalos",               "em_type":   2, "enum_name": "EmType002_00", "dlc": "rise", "tags": []},
    {"name": "Khezu",                  "em_type":   3, "enum_name": "EmType003_00", "dlc": "rise", "tags": []},
    {"name": "Basarios",               "em_type":   4, "enum_name": "EmType004_00", "dlc": "rise", "tags": []},
    {"name": "Diablos",                "em_type":   7, "enum_name": "EmType007_00", "dlc": "rise", "tags": []},
    {"name": "Rajang",                 "em_type":  23, "enum_name": "EmType023_00", "dlc": "rise", "tags": ["elder-dragon"]},
    {"name": "Kushala Daora",          "em_type":  24, "enum_name": "EmType024_00", "dlc": "rise", "tags": ["elder-dragon"]},
    {"name": "Chameleos",              "em_type":  25, "enum_name": "EmType025_00", "dlc": "rise", "tags": ["elder-dragon"]},
    {"name": "Teostra",                "em_type":  27, "enum_name": "EmType027_00", "dlc": "rise", "tags": ["elder-dragon"]},
    {"name": "Tigrex",                 "em_type":  32, "enum_name": "EmType032_00", "dlc": "rise", "tags": []},
    {"name": "Nargacuga",              "em_type":  37, "enum_name": "EmType037_00", "dlc": "rise", "tags": []},
    {"name": "Barioth",                "em_type":  42, "enum_name": "EmType042_00", "dlc": "rise", "tags": []},
    {"name": "Barroth",                "em_type":  44, "enum_name": "EmType044_00", "dlc": "rise", "tags": []},
    {"name": "Royal Ludroth",          "em_type":  47, "enum_name": "EmType047_00", "dlc": "rise", "tags": []},
    {"name": "Great Baggi",            "em_type":  54, "enum_name": "EmType054_00", "dlc": "rise", "tags": []},
    {"name": "Zinogre",                "em_type":  57, "enum_name": "EmType057_00", "dlc": "rise", "tags": []},
    {"name": "Great Wroggi",           "em_type":  59, "enum_name": "EmType059_00", "dlc": "rise", "tags": []},
    {"name": "Arzuros",                "em_type":  60, "enum_name": "EmType060_00", "dlc": "rise", "tags": []},
    {"name": "Lagombi",                "em_type":  61, "enum_name": "EmType061_00", "dlc": "rise", "tags": []},
    {"name": "Volvidon",               "em_type":  62, "enum_name": "EmType062_00", "dlc": "rise", "tags": []},
    {"name": "Mizutsune",              "em_type":  82, "enum_name": "EmType082_00", "dlc": "rise", "tags": []},
    {"name": "Magnamalo",              "em_type":  89, "enum_name": "EmType089_00", "dlc": "rise", "tags": []},
    {"name": "Bishaten",               "em_type":  90, "enum_name": "EmType090_00", "dlc": "rise", "tags": []},
    {"name": "Aknosom",                "em_type":  91, "enum_name": "EmType091_00", "dlc": "rise", "tags": []},
    {"name": "Tetranadon",             "em_type":  92, "enum_name": "EmType092_00", "dlc": "rise", "tags": []},
    {"name": "Somnacanth",             "em_type":  93, "enum_name": "EmType093_00", "dlc": "rise", "tags": []},
    {"name": "Rakna-Kadaki",           "em_type":  94, "enum_name": "EmType094_00", "dlc": "rise", "tags": []},
    {"name": "Almudron",               "em_type":  95, "enum_name": "EmType095_00", "dlc": "rise", "tags": []},
    {"name": "Wind Serpent Ibushi",    "em_type":  96, "enum_name": "EmType096_00", "dlc": "rise", "tags": ["elder-dragon", "non-randomizable"]},
    {"name": "Goss Harag",             "em_type":  97, "enum_name": "EmType097_00", "dlc": "rise", "tags": []},
    {"name": "Great Izuchi",           "em_type":  98, "enum_name": "EmType098_00", "dlc": "rise", "tags": []},
    {"name": "Thunder Serpent Narwa",  "em_type":  99, "enum_name": "EmType099_00", "dlc": "rise", "tags": ["elder-dragon", "non-randomizable"]},
)

# Large monsters added or returning in Sunbreak. Includes new species,
# subspecies / variants of base-game monsters, and the Risen elder dragons.
SUNBREAK_MONSTERS: tuple[dict[str, Any], ...] = (
    # New base-rank Sunbreak monsters
    {"name": "Daimyo Hermitaur",       "em_type":  19, "enum_name": "EmType019_00", "dlc": "sunbreak", "tags": []},
    {"name": "Shogun Ceanataur",       "em_type":  20, "enum_name": "EmType020_00", "dlc": "sunbreak", "tags": []},
    {"name": "Anjanath",               "em_type": 100, "enum_name": "EmType100_00", "dlc": "sunbreak", "tags": []},
    {"name": "Pukei-Pukei",            "em_type": 102, "enum_name": "EmType102_00", "dlc": "sunbreak", "tags": []},
    {"name": "Kulu-Ya-Ku",             "em_type": 107, "enum_name": "EmType107_00", "dlc": "sunbreak", "tags": []},
    {"name": "Jyuratodus",             "em_type": 108, "enum_name": "EmType108_00", "dlc": "sunbreak", "tags": []},
    {"name": "Tobi-Kadachi",           "em_type": 109, "enum_name": "EmType109_00", "dlc": "sunbreak", "tags": []},
    {"name": "Bazelgeuse",             "em_type": 118, "enum_name": "EmType118_00", "dlc": "sunbreak", "tags": []},
    {"name": "Velkhana",               "em_type": 124, "enum_name": "EmType124_00", "dlc": "sunbreak", "tags": ["elder-dragon"]},
    {"name": "Malzeno",                "em_type": 132, "enum_name": "EmType132_00", "dlc": "sunbreak", "tags": ["elder-dragon"]},
    {"name": "Lunagaron",              "em_type": 133, "enum_name": "EmType133_00", "dlc": "sunbreak", "tags": []},
    {"name": "Garangolm",              "em_type": 134, "enum_name": "EmType134_00", "dlc": "sunbreak", "tags": []},
    {"name": "Gaismagorm",             "em_type": 135, "enum_name": "EmType135_00", "dlc": "sunbreak", "tags": ["elder-dragon", "non-randomizable"]},
    {"name": "Espinas",                "em_type": 136, "enum_name": "EmType136_00", "dlc": "sunbreak", "tags": []},
    {"name": "Seregios",               "em_type":  77, "enum_name": "EmType077_00", "dlc": "sunbreak", "tags": []},
    {"name": "Astalos",                "em_type":  81, "enum_name": "EmType081_00", "dlc": "sunbreak", "tags": []},
    {"name": "Gore Magala",            "em_type":  71, "enum_name": "EmType071_00", "dlc": "sunbreak", "tags": []},
    {"name": "Shagaru Magala",         "em_type":  72, "enum_name": "EmType072_00", "dlc": "sunbreak", "tags": ["elder-dragon"]},
    {"name": "Amatsu",                 "em_type":  58, "enum_name": "EmType058_00", "dlc": "sunbreak", "tags": ["elder-dragon"]},

    # Subspecies / variants
    {"name": "Blood Orange Bishaten",  "em_type": 346, "enum_name": "EmType090_01", "dlc": "sunbreak", "tags": []},
    {"name": "Aurora Somnacanth",      "em_type": 349, "enum_name": "EmType093_01", "dlc": "sunbreak", "tags": []},
    {"name": "Pyre Rakna-Kadaki",      "em_type": 350, "enum_name": "EmType094_01", "dlc": "sunbreak", "tags": []},
    {"name": "Magma Almudron",         "em_type": 351, "enum_name": "EmType095_01", "dlc": "sunbreak", "tags": []},
    {"name": "Flaming Espinas",        "em_type": 392, "enum_name": "EmType136_01", "dlc": "sunbreak", "tags": []},
    {"name": "Gold Rathian",           "em_type": 513, "enum_name": "EmType001_02", "dlc": "sunbreak", "tags": []},
    {"name": "Silver Rathalos",        "em_type": 514, "enum_name": "EmType002_02", "dlc": "sunbreak", "tags": []},
    {"name": "Lucent Nargacuga",       "em_type": 549, "enum_name": "EmType037_02", "dlc": "sunbreak", "tags": []},
    {"name": "Violet Mizutsune",       "em_type": 594, "enum_name": "EmType082_02", "dlc": "sunbreak", "tags": []},

    # Title-update endgame monsters
    {"name": "Furious Rajang",         "em_type": 1303, "enum_name": "EmType023_05", "dlc": "sunbreak", "tags": ["elder-dragon"]},
    {"name": "Chaotic Gore Magala",    "em_type": 1351, "enum_name": "EmType071_05", "dlc": "sunbreak", "tags": []},
    {"name": "Crimson Glow Valstrax",  "em_type": 1366, "enum_name": "EmType086_05", "dlc": "sunbreak", "tags": ["elder-dragon"]},
    {"name": "Scorned Magnamalo",      "em_type": 1369, "enum_name": "EmType089_05", "dlc": "sunbreak", "tags": []},
    {"name": "Narwa the Allmother",    "em_type": 1379, "enum_name": "EmType099_05", "dlc": "sunbreak", "tags": ["elder-dragon", "non-randomizable"]},
    {"name": "Seething Bazelgeuse",    "em_type": 1398, "enum_name": "EmType118_05", "dlc": "sunbreak", "tags": []},
    {"name": "Primordial Malzeno",     "em_type": 1412, "enum_name": "EmType132_05", "dlc": "sunbreak", "tags": ["elder-dragon"]},

    # Risen elder dragons (Anomaly Investigation endgame)
    {"name": "Risen Kushala Daora",          "em_type": 2072, "enum_name": "EmType024_08", "dlc": "sunbreak", "tags": ["risen", "elder-dragon"]},
    {"name": "Risen Chameleos",              "em_type": 2073, "enum_name": "EmType025_08", "dlc": "sunbreak", "tags": ["risen", "elder-dragon"]},
    {"name": "Risen Teostra",                "em_type": 2075, "enum_name": "EmType027_08", "dlc": "sunbreak", "tags": ["risen", "elder-dragon"]},
    {"name": "Risen Shagaru Magala",         "em_type": 2120, "enum_name": "EmType072_08", "dlc": "sunbreak", "tags": ["risen", "elder-dragon"]},
    {"name": "Risen Crimson Glow Valstrax",  "em_type": 2134, "enum_name": "EmType086_08", "dlc": "sunbreak", "tags": ["risen", "elder-dragon"]},
)

# Apex variants — rampage-quest exclusives. Excluded from MONSTERS for v1;
# kept here so a future option can enable them.
APEX_MONSTERS: tuple[dict[str, Any], ...] = (
    {"name": "Apex Rathian",   "em_type": 1793, "enum_name": "EmType001_07", "dlc": "sunbreak", "tags": []},
    {"name": "Apex Rathalos",  "em_type": 1794, "enum_name": "EmType002_07", "dlc": "sunbreak", "tags": []},
    {"name": "Apex Diablos",   "em_type": 1799, "enum_name": "EmType007_07", "dlc": "sunbreak", "tags": []},
    {"name": "Apex Zinogre",   "em_type": 1849, "enum_name": "EmType057_07", "dlc": "sunbreak", "tags": []},
    {"name": "Apex Arzuros",   "em_type": 1852, "enum_name": "EmType060_07", "dlc": "sunbreak", "tags": []},
    {"name": "Apex Mizutsune", "em_type": 1874, "enum_name": "EmType082_07", "dlc": "sunbreak", "tags": []},
)

# Small monsters — non-large fauna (Kelbi, Felyne, Bnahabra, Jaggi, etc.).
# Excluded from MONSTERS for v1 because they aren't huntable in the AP sense.
# Kept here so a future option can enable them. Variants with the _05 suffix
# (Frenzy variants) share display names with their base form (Kelbi, Izuchi,
# Kestodon) — they are kept distinct by em_type but flagged via enum_name.
SMALL_MONSTERS: tuple[dict[str, Any], ...] = (
    {"name": "Kelbi",       "em_type": 4099, "enum_name": "EmsType003_00", "dlc": "rise",     "tags": []},
    {"name": "Hornetaur",   "em_type": 4101, "enum_name": "EmsType005_00", "dlc": "rise",     "tags": []},
    {"name": "Vespoid",     "em_type": 4102, "enum_name": "EmsType006_00", "dlc": "rise",     "tags": []},
    {"name": "Felyne",      "em_type": 4103, "enum_name": "EmsType007_00", "dlc": "rise",     "tags": []},
    {"name": "Melynx",      "em_type": 4104, "enum_name": "EmsType008_00", "dlc": "rise",     "tags": []},
    {"name": "Velociprey",  "em_type": 4105, "enum_name": "EmsType009_00", "dlc": "rise",     "tags": []},
    {"name": "Bullfango",   "em_type": 4109, "enum_name": "EmsType013_00", "dlc": "rise",     "tags": []},
    {"name": "Popo",        "em_type": 4110, "enum_name": "EmsType014_00", "dlc": "rise",     "tags": []},
    {"name": "Anteka",      "em_type": 4112, "enum_name": "EmsType016_00", "dlc": "rise",     "tags": []},
    {"name": "Remobra",     "em_type": 4115, "enum_name": "EmsType019_00", "dlc": "rise",     "tags": []},
    {"name": "Hermitaur",   "em_type": 4116, "enum_name": "EmsType020_00", "dlc": "sunbreak", "tags": []},
    {"name": "Ceanataur",   "em_type": 4117, "enum_name": "EmsType021_00", "dlc": "sunbreak", "tags": []},
    {"name": "Rhenoplos",   "em_type": 4121, "enum_name": "EmsType025_00", "dlc": "rise",     "tags": []},
    {"name": "Bnahabra",    "em_type": 4122, "enum_name": "EmsType026_00", "dlc": "rise",     "tags": []},
    {"name": "Altaroth",    "em_type": 4123, "enum_name": "EmsType027_00", "dlc": "rise",     "tags": []},
    {"name": "Gajau",       "em_type": 4125, "enum_name": "EmsType029_00", "dlc": "rise",     "tags": []},
    {"name": "Jaggi",       "em_type": 4130, "enum_name": "EmsType034_00", "dlc": "rise",     "tags": []},
    {"name": "Jaggia",      "em_type": 4131, "enum_name": "EmsType035_00", "dlc": "rise",     "tags": []},
    {"name": "Baggi",       "em_type": 4132, "enum_name": "EmsType036_00", "dlc": "rise",     "tags": []},
    {"name": "Delex",       "em_type": 4134, "enum_name": "EmsType038_00", "dlc": "rise",     "tags": []},
    {"name": "Ludroth",     "em_type": 4135, "enum_name": "EmsType039_00", "dlc": "rise",     "tags": []},
    {"name": "Uroktor",     "em_type": 4136, "enum_name": "EmsType040_00", "dlc": "rise",     "tags": []},
    {"name": "Slagtoth",    "em_type": 4137, "enum_name": "EmsType041_00", "dlc": "rise",     "tags": []},
    {"name": "Gargwa",      "em_type": 4138, "enum_name": "EmsType042_00", "dlc": "rise",     "tags": []},
    {"name": "Wroggi",      "em_type": 4139, "enum_name": "EmsType043_00", "dlc": "rise",     "tags": []},
    {"name": "Zamite",      "em_type": 4140, "enum_name": "EmsType044_00", "dlc": "rise",     "tags": []},
    {"name": "Jagras",      "em_type": 4145, "enum_name": "EmsType049_00", "dlc": "sunbreak", "tags": []},
    {"name": "Kestodon",    "em_type": 4147, "enum_name": "EmsType051_00", "dlc": "sunbreak", "tags": []},
    {"name": "Bombadgy",    "em_type": 4186, "enum_name": "EmsType090_00", "dlc": "rise",     "tags": []},
    {"name": "Izuchi",      "em_type": 4187, "enum_name": "EmsType091_00", "dlc": "rise",     "tags": []},
    {"name": "Rachnoid",    "em_type": 4188, "enum_name": "EmsType092_00", "dlc": "rise",     "tags": []},
    {"name": "Gowngoat",    "em_type": 4189, "enum_name": "EmsType093_00", "dlc": "rise",     "tags": []},
    {"name": "Boggi",       "em_type": 4190, "enum_name": "EmsType094_00", "dlc": "rise",     "tags": []},
    {"name": "Pyrantula",   "em_type": 4444, "enum_name": "EmsType092_01", "dlc": "sunbreak", "tags": []},
    # _05 frenzy variants reuse display names; em_type keeps them distinct
    {"name": "Frenzied Kelbi",     "em_type": 5379, "enum_name": "EmsType003_05", "dlc": "sunbreak", "tags": []},
    {"name": "Frenzied Kestodon",  "em_type": 5427, "enum_name": "EmsType051_05", "dlc": "sunbreak", "tags": []},
    {"name": "Frenzied Izuchi",    "em_type": 5467, "enum_name": "EmsType091_05", "dlc": "sunbreak", "tags": []},
)


# Master list consumed by the apworld. v1: large monsters only.
MONSTERS: tuple[dict[str, Any], ...] = RISE_MONSTERS + SUNBREAK_MONSTERS


# ----- Sanity checks at import time -----

assert len({m["em_type"] for m in MONSTERS}) == len(MONSTERS), "duplicate em_type in MONSTERS"
assert len({m["name"] for m in MONSTERS}) == len(MONSTERS), "duplicate name in MONSTERS"
assert all(m["dlc"] in ("rise", "sunbreak") for m in MONSTERS), "bad dlc tag"
assert all(isinstance(m["tags"], list) for m in MONSTERS), "tags must be a list"

# Cross-bucket uniqueness on em_type, since em_type is the runtime contract
# with the client. (Display name collisions across buckets are fine — frenzy
# small monsters share base names with their non-frenzy form by design.)
_all_em_types = (
    [m["em_type"] for m in MONSTERS]
    + [m["em_type"] for m in APEX_MONSTERS]
    + [m["em_type"] for m in SMALL_MONSTERS]
)
assert len(set(_all_em_types)) == len(_all_em_types), "duplicate em_type across buckets"
